#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/springbtDB
#    username: root
#    password: 123456

server:
  port: 8080
  servlet:
    context-path: /ims/
# mybatis-plus相关配置
mybatis-plus:
  # type-aliases-package: com.wqzeng.ims.entity
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
#  datasource:
#     #serverTimezone=UTC&
#    url: jdbc:mysql://localhost:3306/ims?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: zwq13610018797
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 106.55.57.209
    port: 6379
    password: Zwq10018797
    jedis:
      pool:
        #最大空闲连接
        max-idle: 8
        #最大阻塞等待时间(负值表示无限制)
        max-wait: -1
        #最大连接数
        max-active: 8
        min-idle: 0
    #连接超时时间
    timeout: 5000
